
export type ReoccurringContribution = {
    amount: number;
    frequency: 'Daily' | 'Weekly' | 'Biweekly' | 'Monthly' | 'Quarterly' | 'Annually';
}

export type IContributionDetails = {
    currentValue: number;
    reoccurringContributions: ReoccurringContribution[];
}

export type Investment = {
    symbol: string;
    vender: string;
    price: number;
    averageYearlyReturn: number;
    riskLevel: 'Low' | 'Medium' | 'High';
    contributionDetails?: IContributionDetails;
}

export const riskConfig = {
    Low:    { color: '#00C896', bg: 'rgba(0, 200, 150, 0.1)',  border: 'rgba(0, 200, 150, 0.25)' },
    Medium: { color: '#F5A623', bg: 'rgba(245, 166, 35, 0.1)', border: 'rgba(245, 166, 35, 0.25)' },
    High:   { color: '#FF4D6D', bg: 'rgba(255, 77, 109, 0.1)', border: 'rgba(255, 77, 109, 0.25)' },
}


export const investmentData: Investment[] = [
    // Index Funds
    { symbol: 'FXAIX', vender: 'Fidelity S&P 500 Index', price: 263.97, averageYearlyReturn: 10.5, riskLevel: 'Low' },

    // Information Technology
    { symbol: 'AAPL', vender: 'Apple', price: 227.52, averageYearlyReturn: 22, riskLevel: 'Medium' },
    { symbol: 'MSFT', vender: 'Microsoft', price: 415.25, averageYearlyReturn: 20, riskLevel: 'Medium' },
    { symbol: 'NVDA', vender: 'NVIDIA', price: 131.38, averageYearlyReturn: 45, riskLevel: 'High' },
    { symbol: 'AVGO', vender: 'Broadcom', price: 185.12, averageYearlyReturn: 28, riskLevel: 'High' },
    { symbol: 'ORCL', vender: 'Oracle', price: 174.06, averageYearlyReturn: 13, riskLevel: 'Medium' },
    { symbol: 'CRM', vender: 'Salesforce', price: 312.78, averageYearlyReturn: 16, riskLevel: 'Medium' },
    { symbol: 'AMD', vender: 'Advanced Micro Devices', price: 131.20, averageYearlyReturn: 32, riskLevel: 'High' },
    { symbol: 'CSCO', vender: 'Cisco Systems', price: 58.77, averageYearlyReturn: 8, riskLevel: 'Low' },
    { symbol: 'ACN', vender: 'Accenture', price: 338.29, averageYearlyReturn: 12, riskLevel: 'Medium' },
    { symbol: 'IBM', vender: 'IBM', price: 234.04, averageYearlyReturn: 7, riskLevel: 'Low' },
    { symbol: 'TXN', vender: 'Texas Instruments', price: 191.67, averageYearlyReturn: 10, riskLevel: 'Low' },
    { symbol: 'INTC', vender: 'Intel', price: 20.20, averageYearlyReturn: 3, riskLevel: 'High' },
    { symbol: 'QCOM', vender: 'Qualcomm', price: 155.02, averageYearlyReturn: 14, riskLevel: 'Medium' },
    { symbol: 'AMAT', vender: 'Applied Materials', price: 182.39, averageYearlyReturn: 20, riskLevel: 'High' },
    { symbol: 'MU', vender: 'Micron Technology', price: 102.63, averageYearlyReturn: 18, riskLevel: 'High' },
    { symbol: 'LRCX', vender: 'Lam Research', price: 750.22, averageYearlyReturn: 22, riskLevel: 'High' },
    { symbol: 'KLAC', vender: 'KLA Corporation', price: 656.48, averageYearlyReturn: 22, riskLevel: 'High' },
    { symbol: 'CDNS', vender: 'Cadence Design Systems', price: 295.33, averageYearlyReturn: 18, riskLevel: 'Medium' },
    { symbol: 'SNPS', vender: 'Synopsys', price: 479.55, averageYearlyReturn: 16, riskLevel: 'Medium' },
    { symbol: 'ADSK', vender: 'Autodesk', price: 287.44, averageYearlyReturn: 12, riskLevel: 'Medium' },
    { symbol: 'ANSS', vender: 'Ansys', price: 350.80, averageYearlyReturn: 12, riskLevel: 'Medium' },
    { symbol: 'MSI', vender: 'Motorola Solutions', price: 453.10, averageYearlyReturn: 18, riskLevel: 'Medium' },
    { symbol: 'GDDY', vender: 'GoDaddy', price: 185.45, averageYearlyReturn: 18, riskLevel: 'Medium' },
    { symbol: 'AKAM', vender: 'Akamai Technologies', price: 97.55, averageYearlyReturn: 8, riskLevel: 'Medium' },
    { symbol: 'EPAM', vender: 'EPAM Systems', price: 195.70, averageYearlyReturn: 10, riskLevel: 'High' },
    { symbol: 'CTSH', vender: 'Cognizant Technology', price: 72.34, averageYearlyReturn: 7, riskLevel: 'Low' },
    { symbol: 'IT', vender: 'Gartner', price: 522.80, averageYearlyReturn: 14, riskLevel: 'Medium' },
    { symbol: 'LDOS', vender: 'Leidos Holdings', price: 168.90, averageYearlyReturn: 11, riskLevel: 'Low' },
    { symbol: 'SAIC', vender: 'Science Applications International', price: 122.44, averageYearlyReturn: 9, riskLevel: 'Low' },
    { symbol: 'APH', vender: 'Amphenol', price: 73.55, averageYearlyReturn: 14, riskLevel: 'Medium' },
    { symbol: 'GLW', vender: 'Corning', price: 47.38, averageYearlyReturn: 7, riskLevel: 'Medium' },
    { symbol: 'KEYS', vender: 'Keysight Technologies', price: 135.70, averageYearlyReturn: 10, riskLevel: 'Medium' },
    { symbol: 'TDY', vender: 'Teledyne Technologies', price: 463.22, averageYearlyReturn: 11, riskLevel: 'Medium' },
    { symbol: 'TRMB', vender: 'Trimble', price: 68.90, averageYearlyReturn: 10, riskLevel: 'Medium' },
    { symbol: 'NXPI', vender: 'NXP Semiconductors', price: 218.44, averageYearlyReturn: 12, riskLevel: 'Medium' },
    { symbol: 'MCHP', vender: 'Microchip Technology', price: 60.35, averageYearlyReturn: 10, riskLevel: 'Medium' },
    { symbol: 'SWKS', vender: 'Skyworks Solutions', price: 74.80, averageYearlyReturn: 8, riskLevel: 'Medium' },
    { symbol: 'QRVO', vender: 'Qorvo', price: 65.44, averageYearlyReturn: 8, riskLevel: 'High' },
    { symbol: 'MPWR', vender: 'Monolithic Power Systems', price: 590.25, averageYearlyReturn: 25, riskLevel: 'High' },
    { symbol: 'ON', vender: 'ON Semiconductor', price: 60.55, averageYearlyReturn: 15, riskLevel: 'High' },
    { symbol: 'TE', vender: 'TE Connectivity', price: 147.60, averageYearlyReturn: 10, riskLevel: 'Medium' },
    { symbol: 'HPE', vender: 'Hewlett Packard Enterprise', price: 21.78, averageYearlyReturn: 5, riskLevel: 'Low' },
    { symbol: 'HPQ', vender: 'HP Inc', price: 35.42, averageYearlyReturn: 8, riskLevel: 'Low' },
    { symbol: 'NTAP', vender: 'NetApp', price: 118.95, averageYearlyReturn: 12, riskLevel: 'Medium' },
    { symbol: 'WDC', vender: 'Western Digital', price: 57.80, averageYearlyReturn: 5, riskLevel: 'High' },
    { symbol: 'STX', vender: 'Seagate Technology', price: 95.44, averageYearlyReturn: 8, riskLevel: 'Medium' },
    { symbol: 'VRSN', vender: 'VeriSign', price: 202.30, averageYearlyReturn: 10, riskLevel: 'Low' },
    { symbol: 'GEN', vender: 'Gen Digital', price: 26.50, averageYearlyReturn: 5, riskLevel: 'Low' },
    { symbol: 'FFIV', vender: 'F5 Inc', price: 199.88, averageYearlyReturn: 8, riskLevel: 'Medium' },
    { symbol: 'JNPR', vender: 'Juniper Networks', price: 38.75, averageYearlyReturn: 6, riskLevel: 'Low' },
    { symbol: 'PTC', vender: 'PTC Inc', price: 182.40, averageYearlyReturn: 15, riskLevel: 'Medium' },
    { symbol: 'FTNT', vender: 'Fortinet', price: 93.45, averageYearlyReturn: 20, riskLevel: 'High' },
    { symbol: 'PANW', vender: 'Palo Alto Networks', price: 186.55, averageYearlyReturn: 25, riskLevel: 'High' },
    { symbol: 'NOW', vender: 'ServiceNow', price: 1037.80, averageYearlyReturn: 28, riskLevel: 'High' },
    { symbol: 'ADBE', vender: 'Adobe', price: 436.25, averageYearlyReturn: 18, riskLevel: 'Medium' },
    { symbol: 'INTU', vender: 'Intuit', price: 625.40, averageYearlyReturn: 18, riskLevel: 'Medium' },
    { symbol: 'PLTR', vender: 'Palantir Technologies', price: 85.50, averageYearlyReturn: 30, riskLevel: 'High' },
    { symbol: 'APP', vender: 'Applovin', price: 315.00, averageYearlyReturn: 40, riskLevel: 'High' },
    { symbol: 'ZBRA', vender: 'Zebra Technologies', price: 350.44, averageYearlyReturn: 12, riskLevel: 'Medium' },
    { symbol: 'CDW', vender: 'CDW Corporation', price: 168.90, averageYearlyReturn: 12, riskLevel: 'Medium' },
    { symbol: 'PAYC', vender: 'Paycom Software', price: 155.80, averageYearlyReturn: 14, riskLevel: 'High' },
    { symbol: 'ENPH', vender: 'Enphase Energy', price: 68.40, averageYearlyReturn: 10, riskLevel: 'High' },
    { symbol: 'FSLR', vender: 'First Solar', price: 175.25, averageYearlyReturn: 12, riskLevel: 'High' },

    // Communication Services
    { symbol: 'GOOGL', vender: 'Alphabet Class A', price: 196.08, averageYearlyReturn: 18, riskLevel: 'Medium' },
    { symbol: 'GOOG', vender: 'Alphabet Class C', price: 197.50, averageYearlyReturn: 18, riskLevel: 'Medium' },
    { symbol: 'META', vender: 'Meta Platforms', price: 594.52, averageYearlyReturn: 26, riskLevel: 'Medium' },
    { symbol: 'NFLX', vender: 'Netflix', price: 942.75, averageYearlyReturn: 22, riskLevel: 'Medium' },
    { symbol: 'DIS', vender: 'Walt Disney', price: 96.97, averageYearlyReturn: 8, riskLevel: 'Low' },
    { symbol: 'CMCSA', vender: 'Comcast', price: 36.55, averageYearlyReturn: 7, riskLevel: 'Low' },
    { symbol: 'T', vender: 'AT&T', price: 24.75, averageYearlyReturn: 4, riskLevel: 'Low' },
    { symbol: 'VZ', vender: 'Verizon Communications', price: 41.88, averageYearlyReturn: 4, riskLevel: 'Low' },
    { symbol: 'TMUS', vender: 'T-Mobile US', price: 242.22, averageYearlyReturn: 16, riskLevel: 'Medium' },
    { symbol: 'CHTR', vender: 'Charter Communications', price: 347.80, averageYearlyReturn: 9, riskLevel: 'Medium' },
    { symbol: 'PARA', vender: 'Paramount Global', price: 11.22, averageYearlyReturn: 2, riskLevel: 'High' },
    { symbol: 'WBD', vender: 'Warner Bros Discovery', price: 9.45, averageYearlyReturn: 3, riskLevel: 'High' },
    { symbol: 'EA', vender: 'Electronic Arts', price: 131.50, averageYearlyReturn: 10, riskLevel: 'Medium' },
    { symbol: 'TTWO', vender: 'Take-Two Interactive', price: 178.40, averageYearlyReturn: 10, riskLevel: 'High' },
    { symbol: 'IPG', vender: 'Interpublic Group', price: 26.80, averageYearlyReturn: 5, riskLevel: 'Low' },
    { symbol: 'OMC', vender: 'Omnicom Group', price: 96.55, averageYearlyReturn: 8, riskLevel: 'Low' },
    { symbol: 'FOXA', vender: 'Fox Corporation Class A', price: 46.80, averageYearlyReturn: 8, riskLevel: 'Low' },
    { symbol: 'FOX', vender: 'Fox Corporation Class B', price: 43.90, averageYearlyReturn: 8, riskLevel: 'Low' },
    { symbol: 'LYV', vender: 'Live Nation Entertainment', price: 124.60, averageYearlyReturn: 12, riskLevel: 'High' },
    { symbol: 'MTCH', vender: 'Match Group', price: 30.44, averageYearlyReturn: 4, riskLevel: 'High' },
    { symbol: 'NWSA', vender: 'News Corp Class A', price: 28.90, averageYearlyReturn: 7, riskLevel: 'Low' },
    { symbol: 'NWS', vender: 'News Corp Class B', price: 28.50, averageYearlyReturn: 7, riskLevel: 'Low' },

    // Consumer Discretionary
    { symbol: 'AMZN', vender: 'Amazon', price: 225.89, averageYearlyReturn: 28, riskLevel: 'Medium' },
    { symbol: 'TSLA', vender: 'Tesla', price: 302.80, averageYearlyReturn: 28, riskLevel: 'High' },
    { symbol: 'HD', vender: 'Home Depot', price: 393.14, averageYearlyReturn: 14, riskLevel: 'Low' },
    { symbol: 'MCD', vender: "McDonald's", price: 290.25, averageYearlyReturn: 12, riskLevel: 'Low' },
    { symbol: 'NKE', vender: 'Nike', price: 74.40, averageYearlyReturn: 9, riskLevel: 'Low' },
    { symbol: 'LOW', vender: "Lowe's Companies", price: 242.30, averageYearlyReturn: 14, riskLevel: 'Low' },
    { symbol: 'SBUX', vender: 'Starbucks', price: 96.80, averageYearlyReturn: 10, riskLevel: 'Low' },
    { symbol: 'TJX', vender: 'TJX Companies', price: 122.05, averageYearlyReturn: 14, riskLevel: 'Low' },
    { symbol: 'BKNG', vender: 'Booking Holdings', price: 5025.00, averageYearlyReturn: 18, riskLevel: 'Medium' },
    { symbol: 'CMG', vender: 'Chipotle Mexican Grill', price: 53.80, averageYearlyReturn: 22, riskLevel: 'Medium' },
    { symbol: 'ORLY', vender: "O'Reilly Automotive", price: 1260.00, averageYearlyReturn: 18, riskLevel: 'Medium' },
    { symbol: 'AZO', vender: 'AutoZone', price: 3450.00, averageYearlyReturn: 18, riskLevel: 'Medium' },
    { symbol: 'ROST', vender: 'Ross Stores', price: 148.30, averageYearlyReturn: 14, riskLevel: 'Low' },
    { symbol: 'ABNB', vender: 'Airbnb', price: 141.60, averageYearlyReturn: 14, riskLevel: 'High' },
    { symbol: 'GM', vender: 'General Motors', price: 50.45, averageYearlyReturn: 8, riskLevel: 'Medium' },
    { symbol: 'F', vender: 'Ford Motor', price: 9.88, averageYearlyReturn: 4, riskLevel: 'Medium' },
    { symbol: 'EBAY', vender: 'eBay', price: 64.80, averageYearlyReturn: 8, riskLevel: 'Low' },
    { symbol: 'ETSY', vender: 'Etsy', price: 52.75, averageYearlyReturn: 8, riskLevel: 'High' },
    { symbol: 'ULTA', vender: 'Ulta Beauty', price: 372.50, averageYearlyReturn: 14, riskLevel: 'Medium' },
    { symbol: 'HAS', vender: 'Hasbro', price: 54.80, averageYearlyReturn: 5, riskLevel: 'Low' },
    { symbol: 'MAT', vender: 'Mattel', price: 18.55, averageYearlyReturn: 6, riskLevel: 'Medium' },
    { symbol: 'RL', vender: 'Ralph Lauren', price: 228.90, averageYearlyReturn: 10, riskLevel: 'Medium' },
    { symbol: 'TPR', vender: 'Tapestry', price: 67.80, averageYearlyReturn: 10, riskLevel: 'Medium' },
    { symbol: 'PVH', vender: 'PVH Corp', price: 87.40, averageYearlyReturn: 8, riskLevel: 'Medium' },
    { symbol: 'VFC', vender: 'VF Corporation', price: 14.35, averageYearlyReturn: 2, riskLevel: 'High' },
    { symbol: 'PHM', vender: 'PulteGroup', price: 127.80, averageYearlyReturn: 16, riskLevel: 'Medium' },
    { symbol: 'DHI', vender: 'D.R. Horton', price: 157.25, averageYearlyReturn: 18, riskLevel: 'Medium' },
    { symbol: 'LEN', vender: 'Lennar', price: 141.50, averageYearlyReturn: 15, riskLevel: 'Medium' },
    { symbol: 'TOL', vender: 'Toll Brothers', price: 128.60, averageYearlyReturn: 15, riskLevel: 'Medium' },
    { symbol: 'NVR', vender: 'NVR Inc', price: 9100.00, averageYearlyReturn: 15, riskLevel: 'Medium' },
    { symbol: 'GRMN', vender: 'Garmin', price: 224.80, averageYearlyReturn: 14, riskLevel: 'Medium' },
    { symbol: 'POOL', vender: 'Pool Corporation', price: 338.40, averageYearlyReturn: 12, riskLevel: 'Medium' },
    { symbol: 'MGM', vender: 'MGM Resorts International', price: 34.75, averageYearlyReturn: 10, riskLevel: 'High' },
    { symbol: 'LVS', vender: 'Las Vegas Sands', price: 44.50, averageYearlyReturn: 9, riskLevel: 'High' },
    { symbol: 'WYNN', vender: 'Wynn Resorts', price: 85.30, averageYearlyReturn: 9, riskLevel: 'High' },
    { symbol: 'CZR', vender: 'Caesars Entertainment', price: 30.80, averageYearlyReturn: 7, riskLevel: 'High' },
    { symbol: 'HLT', vender: 'Hilton Worldwide', price: 260.45, averageYearlyReturn: 16, riskLevel: 'Medium' },
    { symbol: 'MAR', vender: 'Marriott International', price: 258.90, averageYearlyReturn: 14, riskLevel: 'Medium' },
    { symbol: 'H', vender: 'Hyatt Hotels', price: 162.30, averageYearlyReturn: 12, riskLevel: 'Medium' },
    { symbol: 'RCL', vender: 'Royal Caribbean Group', price: 230.55, averageYearlyReturn: 22, riskLevel: 'High' },
    { symbol: 'CCL', vender: 'Carnival Corporation', price: 24.90, averageYearlyReturn: 8, riskLevel: 'High' },
    { symbol: 'NCLH', vender: 'Norwegian Cruise Line', price: 21.40, averageYearlyReturn: 8, riskLevel: 'High' },
    { symbol: 'UAL', vender: 'United Airlines', price: 95.80, averageYearlyReturn: 12, riskLevel: 'High' },
    { symbol: 'DAL', vender: 'Delta Air Lines', price: 56.90, averageYearlyReturn: 10, riskLevel: 'High' },
    { symbol: 'AAL', vender: 'American Airlines', price: 13.25, averageYearlyReturn: 4, riskLevel: 'High' },
    { symbol: 'LUV', vender: 'Southwest Airlines', price: 27.50, averageYearlyReturn: 5, riskLevel: 'Medium' },
    { symbol: 'DPZ', vender: "Domino's Pizza", price: 468.20, averageYearlyReturn: 16, riskLevel: 'Low' },
    { symbol: 'YUM', vender: 'Yum! Brands', price: 137.80, averageYearlyReturn: 12, riskLevel: 'Low' },
    { symbol: 'QSR', vender: 'Restaurant Brands International', price: 74.50, averageYearlyReturn: 10, riskLevel: 'Low' },
    { symbol: 'BBY', vender: 'Best Buy', price: 74.35, averageYearlyReturn: 7, riskLevel: 'Medium' },
    { symbol: 'DKNG', vender: 'DraftKings', price: 35.90, averageYearlyReturn: 10, riskLevel: 'High' },
    { symbol: 'PENN', vender: 'PENN Entertainment', price: 15.80, averageYearlyReturn: 4, riskLevel: 'High' },

    // Consumer Staples
    { symbol: 'PG', vender: 'Procter & Gamble', price: 171.25, averageYearlyReturn: 9, riskLevel: 'Low' },
    { symbol: 'KO', vender: 'Coca-Cola', price: 68.90, averageYearlyReturn: 8, riskLevel: 'Low' },
    { symbol: 'PEP', vender: 'PepsiCo', price: 143.80, averageYearlyReturn: 9, riskLevel: 'Low' },
    { symbol: 'COST', vender: 'Costco Wholesale', price: 938.25, averageYearlyReturn: 17, riskLevel: 'Low' },
    { symbol: 'WMT', vender: 'Walmart', price: 93.45, averageYearlyReturn: 13, riskLevel: 'Low' },
    { symbol: 'PM', vender: 'Philip Morris International', price: 134.20, averageYearlyReturn: 9, riskLevel: 'Low' },
    { symbol: 'MO', vender: 'Altria Group', price: 52.30, averageYearlyReturn: 7, riskLevel: 'Low' },
    { symbol: 'CL', vender: 'Colgate-Palmolive', price: 94.55, averageYearlyReturn: 8, riskLevel: 'Low' },
    { symbol: 'KMB', vender: 'Kimberly-Clark', price: 135.60, averageYearlyReturn: 7, riskLevel: 'Low' },
    { symbol: 'HSY', vender: 'Hershey', price: 155.80, averageYearlyReturn: 8, riskLevel: 'Low' },
    { symbol: 'GIS', vender: 'General Mills', price: 57.40, averageYearlyReturn: 7, riskLevel: 'Low' },
    { symbol: 'CPB', vender: "Campbell's", price: 42.80, averageYearlyReturn: 6, riskLevel: 'Low' },
    { symbol: 'HRL', vender: 'Hormel Foods', price: 28.90, averageYearlyReturn: 5, riskLevel: 'Low' },
    { symbol: 'SJM', vender: 'J.M. Smucker', price: 108.75, averageYearlyReturn: 7, riskLevel: 'Low' },
    { symbol: 'MKC', vender: 'McCormick & Company', price: 73.55, averageYearlyReturn: 8, riskLevel: 'Low' },
    { symbol: 'CAG', vender: 'Conagra Brands', price: 25.80, averageYearlyReturn: 5, riskLevel: 'Low' },
    { symbol: 'KHC', vender: 'Kraft Heinz', price: 28.45, averageYearlyReturn: 4, riskLevel: 'Low' },
    { symbol: 'MDLZ', vender: 'Mondelez International', price: 58.30, averageYearlyReturn: 8, riskLevel: 'Low' },
    { symbol: 'STZ', vender: 'Constellation Brands', price: 188.40, averageYearlyReturn: 10, riskLevel: 'Low' },
    { symbol: 'TAP', vender: 'Molson Coors Beverage', price: 54.60, averageYearlyReturn: 6, riskLevel: 'Low' },
    { symbol: 'EL', vender: 'Estee Lauder', price: 74.80, averageYearlyReturn: 7, riskLevel: 'Medium' },
    { symbol: 'CLX', vender: 'Clorox', price: 156.40, averageYearlyReturn: 7, riskLevel: 'Low' },
    { symbol: 'CHD', vender: 'Church & Dwight', price: 103.25, averageYearlyReturn: 10, riskLevel: 'Low' },
    { symbol: 'SYY', vender: 'Sysco', price: 77.80, averageYearlyReturn: 9, riskLevel: 'Low' },
    { symbol: 'KR', vender: 'Kroger', price: 63.45, averageYearlyReturn: 8, riskLevel: 'Low' },
    { symbol: 'SFM', vender: 'Sprouts Farmers Market', price: 148.90, averageYearlyReturn: 16, riskLevel: 'Medium' },
    { symbol: 'MNST', vender: 'Monster Beverage', price: 49.80, averageYearlyReturn: 14, riskLevel: 'Medium' },
    { symbol: 'ADM', vender: 'Archer-Daniels-Midland', price: 46.55, averageYearlyReturn: 7, riskLevel: 'Low' },
    { symbol: 'BG', vender: 'Bunge Global', price: 78.40, averageYearlyReturn: 8, riskLevel: 'Medium' },
    { symbol: 'TSN', vender: 'Tyson Foods', price: 57.80, averageYearlyReturn: 6, riskLevel: 'Low' },

    // Health Care
    { symbol: 'UNH', vender: 'UnitedHealth Group', price: 297.00, averageYearlyReturn: 15, riskLevel: 'Low' },
    { symbol: 'JNJ', vender: 'Johnson & Johnson', price: 153.40, averageYearlyReturn: 8, riskLevel: 'Low' },
    { symbol: 'LLY', vender: 'Eli Lilly', price: 858.75, averageYearlyReturn: 36, riskLevel: 'High' },
    { symbol: 'PFE', vender: 'Pfizer', price: 24.90, averageYearlyReturn: 4, riskLevel: 'Low' },
    { symbol: 'ABBV', vender: 'AbbVie', price: 202.45, averageYearlyReturn: 13, riskLevel: 'Low' },
    { symbol: 'MRK', vender: 'Merck', price: 95.80, averageYearlyReturn: 10, riskLevel: 'Low' },
    { symbol: 'BMY', vender: 'Bristol-Myers Squibb', price: 57.25, averageYearlyReturn: 6, riskLevel: 'Low' },
    { symbol: 'AMGN', vender: 'Amgen', price: 292.80, averageYearlyReturn: 10, riskLevel: 'Low' },
    { symbol: 'GILD', vender: 'Gilead Sciences', price: 93.80, averageYearlyReturn: 8, riskLevel: 'Low' },
    { symbol: 'REGN', vender: 'Regeneron Pharmaceuticals', price: 696.25, averageYearlyReturn: 18, riskLevel: 'High' },
    { symbol: 'VRTX', vender: 'Vertex Pharmaceuticals', price: 458.90, averageYearlyReturn: 22, riskLevel: 'High' },
    { symbol: 'BIIB', vender: 'Biogen', price: 155.40, averageYearlyReturn: 5, riskLevel: 'High' },
    { symbol: 'MRNA', vender: 'Moderna', price: 38.25, averageYearlyReturn: 8, riskLevel: 'High' },
    { symbol: 'DXCM', vender: 'DexCom', price: 71.30, averageYearlyReturn: 14, riskLevel: 'High' },
    { symbol: 'ISRG', vender: 'Intuitive Surgical', price: 547.80, averageYearlyReturn: 20, riskLevel: 'High' },
    { symbol: 'SYK', vender: 'Stryker', price: 395.60, averageYearlyReturn: 14, riskLevel: 'Medium' },
    { symbol: 'BSX', vender: 'Boston Scientific', price: 97.25, averageYearlyReturn: 16, riskLevel: 'Medium' },
    { symbol: 'MDT', vender: 'Medtronic', price: 87.45, averageYearlyReturn: 8, riskLevel: 'Low' },
    { symbol: 'EW', vender: 'Edwards Lifesciences', price: 69.80, averageYearlyReturn: 12, riskLevel: 'Medium' },
    { symbol: 'BAX', vender: 'Baxter International', price: 29.80, averageYearlyReturn: 4, riskLevel: 'Medium' },
    { symbol: 'BDX', vender: 'Becton Dickinson', price: 212.40, averageYearlyReturn: 8, riskLevel: 'Low' },
    { symbol: 'ZBH', vender: 'Zimmer Biomet', price: 105.80, averageYearlyReturn: 8, riskLevel: 'Medium' },
    { symbol: 'HOLX', vender: 'Hologic', price: 68.25, averageYearlyReturn: 10, riskLevel: 'Medium' },
    { symbol: 'IQV', vender: 'IQVIA Holdings', price: 192.80, averageYearlyReturn: 12, riskLevel: 'Medium' },
    { symbol: 'A', vender: 'Agilent Technologies', price: 127.45, averageYearlyReturn: 10, riskLevel: 'Medium' },
    { symbol: 'TMO', vender: 'Thermo Fisher Scientific', price: 520.80, averageYearlyReturn: 14, riskLevel: 'Medium' },
    { symbol: 'DHR', vender: 'Danaher', price: 228.40, averageYearlyReturn: 12, riskLevel: 'Medium' },
    { symbol: 'MTD', vender: 'Mettler-Toledo International', price: 1340.00, averageYearlyReturn: 12, riskLevel: 'Medium' },
    { symbol: 'WAT', vender: 'Waters Corporation', price: 355.80, averageYearlyReturn: 10, riskLevel: 'Medium' },
    { symbol: 'IDXX', vender: 'IDEXX Laboratories', price: 445.25, averageYearlyReturn: 14, riskLevel: 'Medium' },
    { symbol: 'RMD', vender: 'ResMed', price: 237.90, averageYearlyReturn: 14, riskLevel: 'Medium' },
    { symbol: 'ALGN', vender: 'Align Technology', price: 198.75, averageYearlyReturn: 12, riskLevel: 'High' },
    { symbol: 'MCK', vender: 'McKesson', price: 673.80, averageYearlyReturn: 16, riskLevel: 'Medium' },
    { symbol: 'ABC', vender: 'AmerisourceBergen', price: 240.55, averageYearlyReturn: 14, riskLevel: 'Medium' },
    { symbol: 'CAH', vender: 'Cardinal Health', price: 130.40, averageYearlyReturn: 12, riskLevel: 'Low' },
    { symbol: 'CVS', vender: 'CVS Health', price: 47.35, averageYearlyReturn: 6, riskLevel: 'Low' },
    { symbol: 'CI', vender: 'Cigna Group', price: 310.80, averageYearlyReturn: 12, riskLevel: 'Low' },
    { symbol: 'ELV', vender: 'Elevance Health', price: 390.20, averageYearlyReturn: 12, riskLevel: 'Low' },
    { symbol: 'CNC', vender: 'Centene', price: 58.90, averageYearlyReturn: 8, riskLevel: 'Medium' },
    { symbol: 'MOH', vender: 'Molina Healthcare', price: 268.40, averageYearlyReturn: 12, riskLevel: 'Medium' },
    { symbol: 'HCA', vender: 'HCA Healthcare', price: 358.75, averageYearlyReturn: 16, riskLevel: 'Medium' },
    { symbol: 'HUM', vender: 'Humana', price: 254.80, averageYearlyReturn: 10, riskLevel: 'Low' },
    { symbol: 'GEHC', vender: 'GE HealthCare Technologies', price: 87.35, averageYearlyReturn: 11, riskLevel: 'Medium' },
    { symbol: 'INCY', vender: 'Incyte', price: 68.90, averageYearlyReturn: 8, riskLevel: 'High' },
    { symbol: 'PODD', vender: 'Insulet', price: 168.45, averageYearlyReturn: 14, riskLevel: 'High' },
    { symbol: 'RVTY', vender: 'Revvity', price: 105.80, averageYearlyReturn: 10, riskLevel: 'Medium' },
    { symbol: 'TECH', vender: 'Bio-Techne', price: 56.40, averageYearlyReturn: 10, riskLevel: 'Medium' },

    // Financials
    { symbol: 'BRK.B', vender: 'Berkshire Hathaway Class B', price: 490.25, averageYearlyReturn: 11, riskLevel: 'Low' },
    { symbol: 'JPM', vender: 'JPMorgan Chase', price: 310.89, averageYearlyReturn: 12, riskLevel: 'Low' },
    { symbol: 'BAC', vender: 'Bank of America', price: 44.80, averageYearlyReturn: 10, riskLevel: 'Low' },
    { symbol: 'WFC', vender: 'Wells Fargo', price: 76.55, averageYearlyReturn: 10, riskLevel: 'Low' },
    { symbol: 'GS', vender: 'Goldman Sachs', price: 598.40, averageYearlyReturn: 13, riskLevel: 'Low' },
    { symbol: 'MS', vender: 'Morgan Stanley', price: 127.80, averageYearlyReturn: 11, riskLevel: 'Low' },
    { symbol: 'C', vender: 'Citigroup', price: 74.20, averageYearlyReturn: 9, riskLevel: 'Low' },
    { symbol: 'USB', vender: 'U.S. Bancorp', price: 47.35, averageYearlyReturn: 8, riskLevel: 'Low' },
    { symbol: 'PNC', vender: 'PNC Financial Services', price: 188.40, averageYearlyReturn: 10, riskLevel: 'Low' },
    { symbol: 'TFC', vender: 'Truist Financial', price: 45.90, averageYearlyReturn: 8, riskLevel: 'Low' },
    { symbol: 'COF', vender: 'Capital One Financial', price: 195.80, averageYearlyReturn: 13, riskLevel: 'Medium' },
    { symbol: 'AXP', vender: 'American Express', price: 291.25, averageYearlyReturn: 14, riskLevel: 'Low' },
    { symbol: 'V', vender: 'Visa', price: 334.80, averageYearlyReturn: 17, riskLevel: 'Low' },
    { symbol: 'MA', vender: 'Mastercard', price: 537.45, averageYearlyReturn: 17, riskLevel: 'Low' },
    { symbol: 'PYPL', vender: 'PayPal Holdings', price: 79.35, averageYearlyReturn: 8, riskLevel: 'Medium' },
    { symbol: 'FIS', vender: 'Fidelity National Information Services', price: 77.80, averageYearlyReturn: 7, riskLevel: 'Medium' },
    { symbol: 'FISV', vender: 'Fiserv', price: 188.90, averageYearlyReturn: 14, riskLevel: 'Medium' },
    { symbol: 'GPN', vender: 'Global Payments', price: 100.40, averageYearlyReturn: 10, riskLevel: 'Medium' },
    { symbol: 'ICE', vender: 'Intercontinental Exchange', price: 173.80, averageYearlyReturn: 13, riskLevel: 'Medium' },
    { symbol: 'CME', vender: 'CME Group', price: 218.90, averageYearlyReturn: 11, riskLevel: 'Low' },
    { symbol: 'CBOE', vender: 'Cboe Global Markets', price: 208.45, averageYearlyReturn: 10, riskLevel: 'Low' },
    { symbol: 'NDAQ', vender: 'Nasdaq', price: 82.40, averageYearlyReturn: 12, riskLevel: 'Low' },
    { symbol: 'BLK', vender: 'BlackRock', price: 1082.00, averageYearlyReturn: 15, riskLevel: 'Low' },
    { symbol: 'SCHW', vender: 'Charles Schwab', price: 77.45, averageYearlyReturn: 10, riskLevel: 'Low' },
    { symbol: 'TROW', vender: 'T. Rowe Price', price: 105.80, averageYearlyReturn: 10, riskLevel: 'Low' },
    { symbol: 'IVZ', vender: 'Invesco', price: 15.90, averageYearlyReturn: 5, riskLevel: 'Medium' },
    { symbol: 'AMP', vender: 'Ameriprise Financial', price: 530.80, averageYearlyReturn: 15, riskLevel: 'Low' },
    { symbol: 'PRU', vender: 'Prudential Financial', price: 112.45, averageYearlyReturn: 8, riskLevel: 'Low' },
    { symbol: 'MET', vender: 'MetLife', price: 82.30, averageYearlyReturn: 8, riskLevel: 'Low' },
    { symbol: 'AFL', vender: 'Aflac', price: 115.80, averageYearlyReturn: 10, riskLevel: 'Low' },
    { symbol: 'ALL', vender: 'Allstate', price: 215.80, averageYearlyReturn: 10, riskLevel: 'Low' },
    { symbol: 'PGR', vender: 'Progressive', price: 265.40, averageYearlyReturn: 17, riskLevel: 'Low' },
    { symbol: 'TRV', vender: 'Travelers Companies', price: 264.80, averageYearlyReturn: 10, riskLevel: 'Low' },
    { symbol: 'CB', vender: 'Chubb', price: 298.45, averageYearlyReturn: 11, riskLevel: 'Low' },
    { symbol: 'AIG', vender: 'American International Group', price: 78.90, averageYearlyReturn: 8, riskLevel: 'Medium' },
    { symbol: 'HIG', vender: 'Hartford Financial Services', price: 122.45, averageYearlyReturn: 11, riskLevel: 'Low' },
    { symbol: 'GL', vender: 'Globe Life', price: 95.80, averageYearlyReturn: 8, riskLevel: 'Low' },
    { symbol: 'RE', vender: 'Everest Group', price: 388.25, averageYearlyReturn: 10, riskLevel: 'Low' },
    { symbol: 'WRB', vender: 'W.R. Berkley', price: 62.80, averageYearlyReturn: 11, riskLevel: 'Low' },
    { symbol: 'CINF', vender: 'Cincinnati Financial', price: 138.55, averageYearlyReturn: 8, riskLevel: 'Low' },
    { symbol: 'SPGI', vender: 'S&P Global', price: 487.80, averageYearlyReturn: 15, riskLevel: 'Low' },
    { symbol: 'MCO', vender: "Moody's Corporation", price: 462.35, averageYearlyReturn: 15, riskLevel: 'Low' },
    { symbol: 'FNF', vender: 'Fidelity National Financial', price: 57.80, averageYearlyReturn: 9, riskLevel: 'Low' },
    { symbol: 'ALLY', vender: 'Ally Financial', price: 34.80, averageYearlyReturn: 8, riskLevel: 'Medium' },
    { symbol: 'SYF', vender: 'Synchrony Financial', price: 62.45, averageYearlyReturn: 10, riskLevel: 'Medium' },
    { symbol: 'FITB', vender: 'Fifth Third Bancorp', price: 40.80, averageYearlyReturn: 9, riskLevel: 'Low' },
    { symbol: 'HBAN', vender: 'Huntington Bancshares', price: 17.35, averageYearlyReturn: 8, riskLevel: 'Low' },
    { symbol: 'RF', vender: 'Regions Financial', price: 24.80, averageYearlyReturn: 8, riskLevel: 'Low' },
    { symbol: 'KEY', vender: 'KeyCorp', price: 17.45, averageYearlyReturn: 7, riskLevel: 'Low' },
    { symbol: 'CFG', vender: 'Citizens Financial Group', price: 39.80, averageYearlyReturn: 8, riskLevel: 'Low' },
    { symbol: 'MTB', vender: 'M&T Bank', price: 188.45, averageYearlyReturn: 9, riskLevel: 'Low' },
    { symbol: 'ZION', vender: 'Zions Bancorporation', price: 50.80, averageYearlyReturn: 7, riskLevel: 'Medium' },
    { symbol: 'CMA', vender: 'Comerica', price: 54.35, averageYearlyReturn: 7, riskLevel: 'Medium' },
    { symbol: 'NTRS', vender: 'Northern Trust', price: 102.80, averageYearlyReturn: 8, riskLevel: 'Low' },
    { symbol: 'STT', vender: 'State Street', price: 92.45, averageYearlyReturn: 8, riskLevel: 'Low' },
    { symbol: 'BK', vender: 'Bank of New York Mellon', price: 79.80, averageYearlyReturn: 9, riskLevel: 'Low' },
    { symbol: 'BR', vender: 'Broadridge Financial Solutions', price: 228.45, averageYearlyReturn: 12, riskLevel: 'Low' },
    { symbol: 'WU', vender: 'Western Union', price: 9.80, averageYearlyReturn: 3, riskLevel: 'Low' },
    { symbol: 'BEN', vender: 'Franklin Resources', price: 19.35, averageYearlyReturn: 5, riskLevel: 'Low' },

    // Energy
    { symbol: 'XOM', vender: 'ExxonMobil', price: 108.45, averageYearlyReturn: 10, riskLevel: 'Low' },
    { symbol: 'CVX', vender: 'Chevron', price: 148.80, averageYearlyReturn: 9, riskLevel: 'Low' },
    { symbol: 'COP', vender: 'ConocoPhillips', price: 97.45, averageYearlyReturn: 12, riskLevel: 'Low' },
    { symbol: 'EOG', vender: 'EOG Resources', price: 118.90, averageYearlyReturn: 12, riskLevel: 'Medium' },
    { symbol: 'SLB', vender: 'SLB', price: 39.80, averageYearlyReturn: 9, riskLevel: 'Medium' },
    { symbol: 'MPC', vender: 'Marathon Petroleum', price: 145.35, averageYearlyReturn: 14, riskLevel: 'Medium' },
    { symbol: 'PSX', vender: 'Phillips 66', price: 122.80, averageYearlyReturn: 10, riskLevel: 'Medium' },
    { symbol: 'VLO', vender: 'Valero Energy', price: 138.45, averageYearlyReturn: 13, riskLevel: 'Medium' },
    { symbol: 'OXY', vender: 'Occidental Petroleum', price: 46.80, averageYearlyReturn: 10, riskLevel: 'Medium' },
    { symbol: 'DVN', vender: 'Devon Energy', price: 30.45, averageYearlyReturn: 10, riskLevel: 'High' },
    { symbol: 'HAL', vender: 'Halliburton', price: 26.80, averageYearlyReturn: 9, riskLevel: 'Medium' },
    { symbol: 'BKR', vender: 'Baker Hughes', price: 40.25, averageYearlyReturn: 10, riskLevel: 'Medium' },
    { symbol: 'FANG', vender: 'Diamondback Energy', price: 165.80, averageYearlyReturn: 14, riskLevel: 'Medium' },
    { symbol: 'APA', vender: 'APA Corporation', price: 20.35, averageYearlyReturn: 7, riskLevel: 'High' },
    { symbol: 'MRO', vender: 'Marathon Oil', price: 25.80, averageYearlyReturn: 10, riskLevel: 'Medium' },
    { symbol: 'EQT', vender: 'EQT Corporation', price: 40.45, averageYearlyReturn: 11, riskLevel: 'High' },
    { symbol: 'OKE', vender: 'ONEOK', price: 100.80, averageYearlyReturn: 9, riskLevel: 'Low' },
    { symbol: 'WMB', vender: 'Williams Companies', price: 55.35, averageYearlyReturn: 9, riskLevel: 'Low' },
    { symbol: 'KMI', vender: 'Kinder Morgan', price: 27.80, averageYearlyReturn: 7, riskLevel: 'Low' },
    { symbol: 'CTRA', vender: 'Coterra Energy', price: 25.45, averageYearlyReturn: 8, riskLevel: 'Medium' },
    { symbol: 'TRGP', vender: 'Targa Resources', price: 165.80, averageYearlyReturn: 14, riskLevel: 'Medium' },
    { symbol: 'AR', vender: 'Antero Resources', price: 32.45, averageYearlyReturn: 12, riskLevel: 'High' },

    // Industrials
    { symbol: 'GE', vender: 'GE Aerospace', price: 192.80, averageYearlyReturn: 20, riskLevel: 'Medium' },
    { symbol: 'RTX', vender: 'RTX Corporation', price: 128.45, averageYearlyReturn: 10, riskLevel: 'Low' },
    { symbol: 'HON', vender: 'Honeywell International', price: 218.80, averageYearlyReturn: 10, riskLevel: 'Low' },
    { symbol: 'UPS', vender: 'United Parcel Service', price: 104.35, averageYearlyReturn: 8, riskLevel: 'Low' },
    { symbol: 'CAT', vender: 'Caterpillar', price: 378.90, averageYearlyReturn: 14, riskLevel: 'Low' },
    { symbol: 'DE', vender: 'Deere & Company', price: 392.80, averageYearlyReturn: 13, riskLevel: 'Low' },
    { symbol: 'BA', vender: 'Boeing', price: 168.45, averageYearlyReturn: 7, riskLevel: 'Medium' },
    { symbol: 'LMT', vender: 'Lockheed Martin', price: 458.80, averageYearlyReturn: 10, riskLevel: 'Low' },
    { symbol: 'NOC', vender: 'Northrop Grumman', price: 498.35, averageYearlyReturn: 9, riskLevel: 'Low' },
    { symbol: 'GD', vender: 'General Dynamics', price: 272.80, averageYearlyReturn: 9, riskLevel: 'Low' },
    { symbol: 'LHX', vender: 'L3Harris Technologies', price: 232.45, averageYearlyReturn: 9, riskLevel: 'Low' },
    { symbol: 'TDG', vender: 'TransDigm Group', price: 1398.00, averageYearlyReturn: 20, riskLevel: 'High' },
    { symbol: 'HWM', vender: 'Howmet Aerospace', price: 112.80, averageYearlyReturn: 16, riskLevel: 'Medium' },
    { symbol: 'IR', vender: 'Ingersoll Rand', price: 82.45, averageYearlyReturn: 12, riskLevel: 'Medium' },
    { symbol: 'ITW', vender: 'Illinois Tool Works', price: 248.80, averageYearlyReturn: 12, riskLevel: 'Low' },
    { symbol: 'EMR', vender: 'Emerson Electric', price: 110.35, averageYearlyReturn: 10, riskLevel: 'Low' },
    { symbol: 'ETN', vender: 'Eaton Corporation', price: 342.80, averageYearlyReturn: 17, riskLevel: 'Medium' },
    { symbol: 'ROK', vender: 'Rockwell Automation', price: 245.45, averageYearlyReturn: 10, riskLevel: 'Medium' },
    { symbol: 'AME', vender: 'AMETEK', price: 198.80, averageYearlyReturn: 12, riskLevel: 'Medium' },
    { symbol: 'PH', vender: 'Parker-Hannifin', price: 672.35, averageYearlyReturn: 14, riskLevel: 'Medium' },
    { symbol: 'DOV', vender: 'Dover Corporation', price: 188.80, averageYearlyReturn: 10, riskLevel: 'Medium' },
    { symbol: 'FTV', vender: 'Fortive', price: 74.45, averageYearlyReturn: 10, riskLevel: 'Medium' },
    { symbol: 'ROP', vender: 'Roper Technologies', price: 578.80, averageYearlyReturn: 13, riskLevel: 'Medium' },
    { symbol: 'XYL', vender: 'Xylem', price: 126.35, averageYearlyReturn: 11, riskLevel: 'Medium' },
    { symbol: 'OTIS', vender: 'Otis Worldwide', price: 96.80, averageYearlyReturn: 10, riskLevel: 'Low' },
    { symbol: 'CARR', vender: 'Carrier Global', price: 73.45, averageYearlyReturn: 13, riskLevel: 'Medium' },
    { symbol: 'JCI', vender: 'Johnson Controls International', price: 78.80, averageYearlyReturn: 11, riskLevel: 'Medium' },
    { symbol: 'TT', vender: 'Trane Technologies', price: 388.45, averageYearlyReturn: 17, riskLevel: 'Medium' },
    { symbol: 'CHRW', vender: 'C.H. Robinson Worldwide', price: 86.80, averageYearlyReturn: 8, riskLevel: 'Medium' },
    { symbol: 'XPO', vender: 'XPO Inc', price: 152.45, averageYearlyReturn: 14, riskLevel: 'High' },
    { symbol: 'EXPD', vender: 'Expeditors International', price: 122.80, averageYearlyReturn: 10, riskLevel: 'Low' },
    { symbol: 'JBHT', vender: 'J.B. Hunt Transport Services', price: 165.35, averageYearlyReturn: 9, riskLevel: 'Low' },
    { symbol: 'SAIA', vender: 'Saia Inc', price: 428.80, averageYearlyReturn: 14, riskLevel: 'Medium' },
    { symbol: 'ODFL', vender: 'Old Dominion Freight Line', price: 182.45, averageYearlyReturn: 14, riskLevel: 'Low' },
    { symbol: 'WAB', vender: 'Wabtec', price: 192.80, averageYearlyReturn: 13, riskLevel: 'Medium' },
    { symbol: 'CSX', vender: 'CSX Corporation', price: 33.45, averageYearlyReturn: 10, riskLevel: 'Low' },
    { symbol: 'NSC', vender: 'Norfolk Southern', price: 228.80, averageYearlyReturn: 10, riskLevel: 'Low' },
    { symbol: 'UNP', vender: 'Union Pacific', price: 232.45, averageYearlyReturn: 10, riskLevel: 'Low' },
    { symbol: 'FAST', vender: 'Fastenal', price: 79.80, averageYearlyReturn: 14, riskLevel: 'Low' },
    { symbol: 'GWW', vender: 'W.W. Grainger', price: 1125.00, averageYearlyReturn: 14, riskLevel: 'Low' },
    { symbol: 'AOS', vender: 'A.O. Smith', price: 68.45, averageYearlyReturn: 10, riskLevel: 'Low' },
    { symbol: 'MAS', vender: 'Masco', price: 74.80, averageYearlyReturn: 10, riskLevel: 'Low' },
    { symbol: 'FLR', vender: 'Fluor Corporation', price: 45.35, averageYearlyReturn: 8, riskLevel: 'Medium' },
    { symbol: 'EME', vender: 'EMCOR Group', price: 412.80, averageYearlyReturn: 20, riskLevel: 'Medium' },
    { symbol: 'PWR', vender: 'Quanta Services', price: 318.45, averageYearlyReturn: 16, riskLevel: 'Medium' },
    { symbol: 'MTZ', vender: 'MasTec', price: 142.80, averageYearlyReturn: 14, riskLevel: 'High' },
    { symbol: 'GEV', vender: 'GE Vernova', price: 378.45, averageYearlyReturn: 18, riskLevel: 'High' },
    { symbol: 'GNRC', vender: 'Generac Holdings', price: 148.80, averageYearlyReturn: 10, riskLevel: 'High' },
    { symbol: 'AXON', vender: 'Axon Enterprise', price: 608.45, averageYearlyReturn: 28, riskLevel: 'High' },
    { symbol: 'ADP', vender: 'Automatic Data Processing', price: 308.80, averageYearlyReturn: 13, riskLevel: 'Low' },
    { symbol: 'PAYX', vender: 'Paychex', price: 148.45, averageYearlyReturn: 12, riskLevel: 'Low' },
    { symbol: 'VRSK', vender: 'Verisk Analytics', price: 285.80, averageYearlyReturn: 13, riskLevel: 'Low' },
    { symbol: 'EFX', vender: 'Equifax', price: 270.45, averageYearlyReturn: 12, riskLevel: 'Medium' },
    { symbol: 'CPRT', vender: 'Copart', price: 58.80, averageYearlyReturn: 20, riskLevel: 'Medium' },
    { symbol: 'RSG', vender: 'Republic Services', price: 222.45, averageYearlyReturn: 14, riskLevel: 'Low' },
    { symbol: 'WM', vender: 'Waste Management', price: 218.80, averageYearlyReturn: 13, riskLevel: 'Low' },
    { symbol: 'CTAS', vender: 'Cintas Corporation', price: 196.45, averageYearlyReturn: 16, riskLevel: 'Low' },
    { symbol: 'RHI', vender: 'Robert Half International', price: 52.80, averageYearlyReturn: 7, riskLevel: 'Low' },
    { symbol: 'TXT', vender: 'Textron', price: 74.35, averageYearlyReturn: 8, riskLevel: 'Medium' },
    { symbol: 'HII', vender: 'Huntington Ingalls Industries', price: 188.80, averageYearlyReturn: 8, riskLevel: 'Low' },
    { symbol: 'ALSN', vender: 'Allison Transmission', price: 95.45, averageYearlyReturn: 12, riskLevel: 'Low' },
    { symbol: 'FDX', vender: 'FedEx', price: 248.80, averageYearlyReturn: 10, riskLevel: 'Medium' },
    { symbol: 'J', vender: 'Jacobs Solutions', price: 118.35, averageYearlyReturn: 10, riskLevel: 'Medium' },
    { symbol: 'KBR', vender: 'KBR Inc', price: 72.80, averageYearlyReturn: 11, riskLevel: 'Medium' },

    // Materials
    { symbol: 'LIN', vender: 'Linde', price: 468.45, averageYearlyReturn: 13, riskLevel: 'Low' },
    { symbol: 'APD', vender: 'Air Products and Chemicals', price: 275.80, averageYearlyReturn: 9, riskLevel: 'Low' },
    { symbol: 'SHW', vender: 'Sherwin-Williams', price: 358.45, averageYearlyReturn: 14, riskLevel: 'Low' },
    { symbol: 'ECL', vender: 'Ecolab', price: 248.80, averageYearlyReturn: 12, riskLevel: 'Low' },
    { symbol: 'DD', vender: 'DuPont de Nemours', price: 82.35, averageYearlyReturn: 8, riskLevel: 'Medium' },
    { symbol: 'DOW', vender: 'Dow Inc', price: 35.80, averageYearlyReturn: 6, riskLevel: 'Low' },
    { symbol: 'LYB', vender: 'LyondellBasell Industries', price: 72.45, averageYearlyReturn: 7, riskLevel: 'Low' },
    { symbol: 'PPG', vender: 'PPG Industries', price: 110.80, averageYearlyReturn: 8, riskLevel: 'Low' },
    { symbol: 'RPM', vender: 'RPM International', price: 132.45, averageYearlyReturn: 10, riskLevel: 'Low' },
    { symbol: 'IFF', vender: 'International Flavors & Fragrances', price: 78.80, averageYearlyReturn: 6, riskLevel: 'Medium' },
    { symbol: 'EMN', vender: 'Eastman Chemical', price: 82.35, averageYearlyReturn: 8, riskLevel: 'Medium' },
    { symbol: 'CE', vender: 'Celanese', price: 48.80, averageYearlyReturn: 6, riskLevel: 'Medium' },
    { symbol: 'WLK', vender: 'Westlake Corporation', price: 105.45, averageYearlyReturn: 8, riskLevel: 'Medium' },
    { symbol: 'CF', vender: 'CF Industries Holdings', price: 78.80, averageYearlyReturn: 10, riskLevel: 'Medium' },
    { symbol: 'MOS', vender: 'Mosaic', price: 24.35, averageYearlyReturn: 5, riskLevel: 'Medium' },
    { symbol: 'NUE', vender: 'Nucor', price: 138.80, averageYearlyReturn: 12, riskLevel: 'Low' },
    { symbol: 'STLD', vender: 'Steel Dynamics', price: 118.45, averageYearlyReturn: 13, riskLevel: 'Medium' },
    { symbol: 'RS', vender: 'Reliance Steel & Aluminum', price: 298.80, averageYearlyReturn: 13, riskLevel: 'Low' },
    { symbol: 'ATI', vender: 'ATI Inc', price: 58.35, averageYearlyReturn: 13, riskLevel: 'Medium' },
    { symbol: 'AA', vender: 'Alcoa', price: 32.80, averageYearlyReturn: 7, riskLevel: 'High' },
    { symbol: 'NEM', vender: 'Newmont', price: 48.45, averageYearlyReturn: 8, riskLevel: 'Medium' },
    { symbol: 'FCX', vender: 'Freeport-McMoRan', price: 43.80, averageYearlyReturn: 11, riskLevel: 'High' },
    { symbol: 'IP', vender: 'International Paper', price: 48.35, averageYearlyReturn: 7, riskLevel: 'Low' },
    { symbol: 'PKG', vender: 'Packaging Corporation of America', price: 212.80, averageYearlyReturn: 11, riskLevel: 'Low' },
    { symbol: 'SEE', vender: 'Sealed Air', price: 28.45, averageYearlyReturn: 5, riskLevel: 'Medium' },
    { symbol: 'VMC', vender: 'Vulcan Materials', price: 258.80, averageYearlyReturn: 13, riskLevel: 'Low' },
    { symbol: 'MLM', vender: 'Martin Marietta Materials', price: 598.45, averageYearlyReturn: 13, riskLevel: 'Low' },
    { symbol: 'BALL', vender: 'Ball Corporation', price: 58.80, averageYearlyReturn: 9, riskLevel: 'Low' },
    { symbol: 'SON', vender: 'Sonoco Products', price: 42.35, averageYearlyReturn: 6, riskLevel: 'Low' },
    { symbol: 'AMCR', vender: 'Amcor', price: 11.80, averageYearlyReturn: 5, riskLevel: 'Low' },
    { symbol: 'OLN', vender: 'Olin Corporation', price: 22.45, averageYearlyReturn: 6, riskLevel: 'Medium' },

    // Real Estate
    { symbol: 'AMT', vender: 'American Tower', price: 185.80, averageYearlyReturn: 9, riskLevel: 'Medium' },
    { symbol: 'PLD', vender: 'Prologis', price: 108.45, averageYearlyReturn: 10, riskLevel: 'Low' },
    { symbol: 'EQIX', vender: 'Equinix', price: 878.80, averageYearlyReturn: 11, riskLevel: 'Medium' },
    { symbol: 'CCI', vender: 'Crown Castle', price: 88.45, averageYearlyReturn: 7, riskLevel: 'Medium' },
    { symbol: 'SPG', vender: 'Simon Property Group', price: 158.80, averageYearlyReturn: 8, riskLevel: 'Low' },
    { symbol: 'O', vender: 'Realty Income', price: 53.45, averageYearlyReturn: 7, riskLevel: 'Low' },
    { symbol: 'PSA', vender: 'Public Storage', price: 295.80, averageYearlyReturn: 9, riskLevel: 'Low' },
    { symbol: 'DLR', vender: 'Digital Realty Trust', price: 162.45, averageYearlyReturn: 10, riskLevel: 'Medium' },
    { symbol: 'WELL', vender: 'Welltower', price: 128.80, averageYearlyReturn: 10, riskLevel: 'Low' },
    { symbol: 'VTR', vender: 'Ventas', price: 54.45, averageYearlyReturn: 7, riskLevel: 'Low' },
    { symbol: 'EXR', vender: 'Extra Space Storage', price: 142.80, averageYearlyReturn: 9, riskLevel: 'Low' },
    { symbol: 'CBRE', vender: 'CBRE Group', price: 128.45, averageYearlyReturn: 14, riskLevel: 'Medium' },
    { symbol: 'BXP', vender: 'BXP Inc', price: 65.80, averageYearlyReturn: 5, riskLevel: 'Medium' },
    { symbol: 'KIM', vender: 'Kimco Realty', price: 23.45, averageYearlyReturn: 6, riskLevel: 'Low' },
    { symbol: 'REG', vender: 'Regency Centers', price: 68.80, averageYearlyReturn: 7, riskLevel: 'Low' },
    { symbol: 'FRT', vender: 'Federal Realty Investment Trust', price: 105.45, averageYearlyReturn: 6, riskLevel: 'Low' },
    { symbol: 'NNN', vender: 'NNN REIT', price: 42.80, averageYearlyReturn: 5, riskLevel: 'Low' },
    { symbol: 'VICI', vender: 'VICI Properties', price: 30.45, averageYearlyReturn: 7, riskLevel: 'Low' },
    { symbol: 'PEAK', vender: 'Healthpeak Properties', price: 20.80, averageYearlyReturn: 5, riskLevel: 'Low' },
    { symbol: 'ARE', vender: 'Alexandria Real Estate Equities', price: 98.45, averageYearlyReturn: 6, riskLevel: 'Medium' },
    { symbol: 'EQR', vender: 'Equity Residential', price: 68.80, averageYearlyReturn: 6, riskLevel: 'Low' },
    { symbol: 'AVB', vender: 'AvalonBay Communities', price: 218.45, averageYearlyReturn: 7, riskLevel: 'Low' },
    { symbol: 'UDR', vender: 'UDR Inc', price: 36.80, averageYearlyReturn: 5, riskLevel: 'Low' },
    { symbol: 'ESS', vender: 'Essex Property Trust', price: 272.45, averageYearlyReturn: 7, riskLevel: 'Low' },
    { symbol: 'MAA', vender: 'Mid-America Apartment Communities', price: 138.80, averageYearlyReturn: 7, riskLevel: 'Low' },
    { symbol: 'CPT', vender: 'Camden Property Trust', price: 112.45, averageYearlyReturn: 7, riskLevel: 'Low' },
    { symbol: 'INVH', vender: 'Invitation Homes', price: 32.80, averageYearlyReturn: 7, riskLevel: 'Low' },
    { symbol: 'AMH', vender: 'American Homes 4 Rent', price: 38.45, averageYearlyReturn: 7, riskLevel: 'Low' },
    { symbol: 'CUBE', vender: 'CubeSmart', price: 43.80, averageYearlyReturn: 6, riskLevel: 'Low' },
    { symbol: 'REXR', vender: 'Rexford Industrial Realty', price: 42.45, averageYearlyReturn: 9, riskLevel: 'Medium' },
    { symbol: 'EGP', vender: 'EastGroup Properties', price: 168.80, averageYearlyReturn: 10, riskLevel: 'Medium' },

    // Utilities
    { symbol: 'NEE', vender: 'NextEra Energy', price: 70.45, averageYearlyReturn: 9, riskLevel: 'Low' },
    { symbol: 'DUK', vender: 'Duke Energy', price: 108.80, averageYearlyReturn: 6, riskLevel: 'Low' },
    { symbol: 'SO', vender: 'Southern Company', price: 90.45, averageYearlyReturn: 6, riskLevel: 'Low' },
    { symbol: 'D', vender: 'Dominion Energy', price: 44.80, averageYearlyReturn: 5, riskLevel: 'Low' },
    { symbol: 'AEP', vender: 'American Electric Power', price: 102.45, averageYearlyReturn: 6, riskLevel: 'Low' },
    { symbol: 'XEL', vender: 'Xcel Energy', price: 66.80, averageYearlyReturn: 6, riskLevel: 'Low' },
    { symbol: 'PCG', vender: 'PG&E Corporation', price: 18.45, averageYearlyReturn: 6, riskLevel: 'Medium' },
    { symbol: 'EXC', vender: 'Exelon', price: 40.80, averageYearlyReturn: 5, riskLevel: 'Low' },
    { symbol: 'ED', vender: 'Consolidated Edison', price: 100.45, averageYearlyReturn: 5, riskLevel: 'Low' },
    { symbol: 'PEG', vender: 'Public Service Enterprise Group', price: 88.80, averageYearlyReturn: 7, riskLevel: 'Low' },
    { symbol: 'ES', vender: 'Eversource Energy', price: 57.45, averageYearlyReturn: 5, riskLevel: 'Low' },
    { symbol: 'WEC', vender: 'WEC Energy Group', price: 92.80, averageYearlyReturn: 6, riskLevel: 'Low' },
    { symbol: 'ETR', vender: 'Entergy', price: 128.45, averageYearlyReturn: 7, riskLevel: 'Low' },
    { symbol: 'FE', vender: 'FirstEnergy', price: 43.80, averageYearlyReturn: 5, riskLevel: 'Low' },
    { symbol: 'AEE', vender: 'Ameren', price: 92.45, averageYearlyReturn: 6, riskLevel: 'Low' },
    { symbol: 'LNT', vender: 'Alliant Energy', price: 58.80, averageYearlyReturn: 6, riskLevel: 'Low' },
    { symbol: 'CMS', vender: 'CMS Energy', price: 70.45, averageYearlyReturn: 6, riskLevel: 'Low' },
    { symbol: 'CNP', vender: 'CenterPoint Energy', price: 32.80, averageYearlyReturn: 5, riskLevel: 'Low' },
    { symbol: 'NI', vender: 'NiSource', price: 36.45, averageYearlyReturn: 5, riskLevel: 'Low' },
    { symbol: 'PPL', vender: 'PPL Corporation', price: 35.80, averageYearlyReturn: 6, riskLevel: 'Low' },
    { symbol: 'EVRG', vender: 'Evergy', price: 58.45, averageYearlyReturn: 5, riskLevel: 'Low' },
    { symbol: 'ATO', vender: 'Atmos Energy', price: 142.80, averageYearlyReturn: 7, riskLevel: 'Low' },
    { symbol: 'SRE', vender: 'Sempra', price: 74.45, averageYearlyReturn: 7, riskLevel: 'Low' },
    { symbol: 'AWK', vender: 'American Water Works', price: 138.80, averageYearlyReturn: 8, riskLevel: 'Low' },
    { symbol: 'CEG', vender: 'Constellation Energy', price: 322.45, averageYearlyReturn: 18, riskLevel: 'Medium' },
    { symbol: 'VST', vender: 'Vistra', price: 158.80, averageYearlyReturn: 22, riskLevel: 'High' },
    { symbol: 'NRG', vender: 'NRG Energy', price: 128.45, averageYearlyReturn: 14, riskLevel: 'Medium' },
    { symbol: 'EIX', vender: 'Edison International', price: 52.80, averageYearlyReturn: 5, riskLevel: 'Low' },
    { symbol: 'WTRG', vender: 'Essential Utilities', price: 24.45, averageYearlyReturn: 5, riskLevel: 'Low' },
]

